CREATE TABLE sleep_log(
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_sleep  TIMESTAMP   NOT NULL,
    end_sleep    TIMESTAMP   NOT NULL,
    morning_mood VARCHAR(64) NOT NULL
);