CREATE TABLE users(
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(128)   NOT NULL,
    last_name    VARCHAR(128)   NOT NULL
);

INSERT INTO users(first_name, last_name)
VALUES ('Tony', 'Stark'), ('Dwight', 'Schrute');